<?php
$models = [
    'Asset' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\MorphMany;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Asset extends Model\n{\n    use HasUuids;\n\n    protected \$guarded = [];\n\n    public function category(): BelongsTo\n    {\n        return \$this->belongsTo(AssetCategory::class, 'category_id');\n    }\n\n    public function room(): BelongsTo\n    {\n        return \$this->belongsTo(Room::class, 'room_id');\n    }\n\n    public function media(): MorphMany\n    {\n        return \$this->morphMany(Media::class, 'mediable');\n    }\n\n    public function identifiers(): HasMany\n    {\n        return \$this->hasMany(AssetIdentifier::class, 'asset_id');\n    }\n\n    public function components(): HasMany\n    {\n        return \$this->hasMany(AssetComponent::class, 'asset_id');\n    }\n\n    public function occupancies(): HasMany\n    {\n        return \$this->hasMany(AssetOccupancy::class, 'asset_id');\n    }\n}\n",
    'Media' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\MorphTo;\n\nclass Media extends Model\n{\n    protected \$guarded = [];\n\n    public function mediable(): MorphTo\n    {\n        return \$this->morphTo();\n    }\n}\n",
    'AssetCategory' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass AssetCategory extends Model\n{\n    protected \$guarded = [];\n\n    public function parent(): BelongsTo\n    {\n        return \$this->belongsTo(AssetCategory::class, 'parent_id');\n    }\n\n    public function children(): HasMany\n    {\n        return \$this->hasMany(AssetCategory::class, 'parent_id');\n    }\n\n    public function assets(): HasMany\n    {\n        return \$this->hasMany(Asset::class, 'category_id');\n    }\n}\n"
];

foreach ($models as $name => $content) {
    file_put_contents("c:\\laragon\\www\\bmn-gakkum-jambi\\app\\Models\\$name.php", $content);
}
echo "Done";
