<?php
$controllers = [
    'MaintenanceController' => "<?php\n\nnamespace App\Http\Controllers;\n\nuse App\Models\Asset;\nuse App\Models\MaintenanceLog;\nuse Illuminate\Http\Request;\nuse Illuminate\Support\Facades\DB;\n\nclass MaintenanceController extends Controller\n{\n    public function store(Request \$request)\n    {\n        \$validated = \$request->validate([\n            'asset_id' => 'required|exists:assets,id',\n            'description' => 'required|string',\n            'cost' => 'nullable|numeric|min:0',\n            'start_date' => 'required|date',\n            'end_date' => 'nullable|date|after_or_equal:start_date'\n        ]);\n\n        DB::transaction(function() use (\$validated, \$request) {\n            MaintenanceLog::create([\n                'asset_id' => \$validated['asset_id'],\n                'description' => \$validated['description'],\n                'cost' => \$validated['cost'] ?? 0,\n                'start_date' => \$validated['start_date'],\n                'end_date' => \$validated['end_date'] ?? null,\n                'status' => empty(\$validated['end_date']) ? 'in_progress' : 'completed',\n                'reported_by' => \$request->user()->id\n            ]);\n\n            if (!empty(\$validated['end_date'])) {\n                Asset::where('id', \$validated['asset_id'])->update(['condition' => 'Baik']);\n            }\n        });\n\n        return back()->with('success', 'Catatan perawatan berhasil disimpan.');\n    }\n}\n",
    
    'DisposalController' => "<?php\n\nnamespace App\Http\Controllers;\n\nuse App\Models\Asset;\nuse App\Models\Disposal;\nuse Illuminate\Http\Request;\nuse Illuminate\Support\Facades\DB;\n\nclass DisposalController extends Controller\n{\n    public function propose(Request \$request, Asset \$asset)\n    {\n        \$request->validate([\n            'reason' => 'required|string'\n        ]);\n\n        Disposal::create([\n            'asset_id' => \$asset->id,\n            'reason' => \$request->reason,\n            'status' => 'proposed',\n            'proposed_by' => \$request->user()->id\n        ]);\n\n        return back()->with('success', 'Usulan penghapusan BMN berhasil diajukan.');\n    }\n\n    public function approve(Request \$request, Disposal \$disposal)\n    {\n        // AC-21: Finalisasi penghapusan tanpa SK ditolak\n        \$request->validate([\n            'sk_number' => 'required|string'\n        ]);\n\n        DB::transaction(function() use (\$request, \$disposal) {\n            \$disposal->update([\n                'sk_number' => \$request->sk_number,\n                'status' => 'approved',\n                'approved_by' => \$request->user()->id\n            ]);\n\n            \$disposal->asset->update([\n                'status' => 'disposed'\n            ]);\n        });\n\n        return back()->with('success', 'Penghapusan BMN disetujui (SK tervalidasi) dan aset diarsipkan.');\n    }\n}\n",
    
    'SpipController' => "<?php\n\nnamespace App\Http\Controllers;\n\nuse App\Models\SpipRecord;\nuse Illuminate\Http\Request;\nuse Inertia\Inertia;\n\nclass SpipController extends Controller\n{\n    public function index()\n    {\n        \$records = SpipRecord::with(['asset', 'assessor'])->latest()->paginate(15);\n        return Inertia::render('Spip/Index', ['records' => \$records]);\n    }\n\n    public function store(Request \$request)\n    {\n        \$validated = \$request->validate([\n            'period' => 'required|string',\n            'asset_id' => 'nullable|exists:assets,id',\n            'risk_description' => 'required|string',\n            'control_action' => 'required|string'\n        ]);\n\n        SpipRecord::create([\n            'period' => \$validated['period'],\n            'asset_id' => \$validated['asset_id'] ?? null,\n            'risk_description' => \$validated['risk_description'],\n            'control_action' => \$validated['control_action'],\n            'status' => 'open',\n            'assessor_id' => \$request->user()->id\n        ]);\n\n        return back()->with('success', 'Rekaman SPIP BMN berhasil ditambahkan.');\n    }\n}\n"
];

foreach (\$controllers as \$name => \$content) {
    file_put_contents("c:\\laragon\\www\\bmn-gakkum-jambi\\app\\Http\\Controllers\\\$name.php", \$content);
}
echo "Done";
