import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'Figtree', ...defaultTheme.fontFamily.sans],
                'display-lg': ['Inter', 'sans-serif'],
                'headline-xl': ['Inter', 'sans-serif'],
                'headline-lg': ['Inter', 'sans-serif'],
                'headline-sm': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'body-sm': ['Inter', 'sans-serif'],
                'label-lg': ['Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'label-sm': ['Inter', 'sans-serif'],
                'data-metric': ['Inter', 'sans-serif'],
            },
            colors: {
                'inverse-on-surface': '#f4eeff',
                'secondary-container': '#ff8010',
                'surface-container-lowest': '#ffffff',
                'secondary-fixed-dim': '#ffb689',
                'surface': '#fdf8ff',
                'tertiary-container': '#004d98',
                'on-secondary': '#ffffff',
                'surface-bright': '#fdf8ff',
                'on-secondary-fixed': '#311300',
                'surface-dim': '#ded5fb',
                'on-tertiary-fixed-variant': '#00468b',
                'on-primary-fixed-variant': '#005049',
                'primary': '#003f39',
                'on-tertiary-container': '#9dc0ff',
                'inverse-surface': '#322c4a',
                'surface-variant': '#e6deff',
                'outline': '#6f7977',
                'on-tertiary': '#ffffff',
                'on-secondary-container': '#5f2b00',
                'primary-container': '#015850',
                'on-primary-container': '#87ccc1',
                'on-background': '#1c1733',
                'background': '#fdf8ff',
                'on-primary-fixed': '#00201c',
                'on-tertiary-fixed': '#001b3d',
                'error-container': '#ffdad6',
                'surface-container': '#f1ebff',
                'secondary': '#974800',
                'tertiary-fixed-dim': '#a9c7ff',
                'error': '#ba1a1a',
                'primary-fixed-dim': '#8ed3c9',
                'surface-container-low': '#f7f1ff',
                'inverse-primary': '#8ed3c9',
                'on-surface': '#1c1733',
                'tertiary': '#00366f',
                'surface-container-highest': '#e6deff',
                'tertiary-fixed': '#d6e3ff',
                'on-surface-variant': '#3f4947',
                'on-secondary-fixed-variant': '#733500',
                'on-error-container': '#93000a',
                'surface-tint': '#1f6961',
                'on-primary': '#ffffff',
                'outline-variant': '#bec9c6',
                'surface-container-high': '#ece4ff',
                'on-error': '#ffffff',
                'primary-fixed': '#aaf0e5',
                'secondary-fixed': '#ffdbc7',
            },
            borderRadius: {
                DEFAULT: '0.5rem',
                sm: '0.25rem',
                md: '0.75rem',
                lg: '1rem',
                xl: '1.5rem',
                full: '9999px',
            },
            spacing: {
                'space-xs': '0.25rem',
                'space-sm': '0.5rem',
                'space-md': '1rem',
                'space-lg': '1.5rem',
                'space-xl': '2rem',
                'gutter': '1.5rem',
                'gutter-mobile': '1rem',
                'margin': '2rem',
                'margin-mobile': '1rem',
            },
        },
    },

    plugins: [forms],
};
