import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, usePage } from '@inertiajs/react';
import ActionForm, { Field } from '@/Components/ActionForm';
import Pagination from '@/Components/Pagination';
import { PageProps } from '@/types';

export default function Administration({ users, units, rooms, categories, isGlobal }: any) {
    const { auth } = usePage<PageProps>().props;
    const unit: Field = { name: 'unit_id', label: 'Unit penugasan', type: 'select', required: false, options: units.map((u: any) => ({ value: u.id, label: u.name })) };
    return <AuthenticatedLayout header={<h1 className="text-2xl font-bold">Administrasi akun & organisasi</h1>}>
        <Head title="Administrasi" /><p className="mb-6 text-sm text-slate-600">Mandat administrasi terpisah dari role operasional. Aktivasi membutuhkan email terverifikasi; perubahan akun sendiri tidak diizinkan.</p>
        <div className="mb-7 flex flex-wrap gap-3">{['unit', 'room', 'category'].filter(kind => isGlobal || kind === 'room').map(kind => <ActionForm key={kind} title={'Tambah ' + ({ unit: 'unit', room: 'ruangan', category: 'kategori' } as Record<string, string>)[kind]} url={route('administration.organization', kind)} fields={[{ name: 'name', label: 'Nama' }, { name: 'code', label: 'Kode' }, ...(kind === 'room' ? [{ ...unit, required: true }] : [])]} />)}</div>
        {isGlobal && <Link href={route('placement.index')} className="simon-button-secondary mb-6">Kelompokkan aset yang belum memiliki ruangan →</Link>}
        <h2 className="mb-4 text-lg font-bold">Pengguna</h2><div className="space-y-3">{users.data.map((user: any) => <section key={user.id} className="simon-card"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-semibold">{user.name}</h3><p className="mt-1 text-sm text-slate-500">{user.email} · {user.status} · {user.email_verified_at ? 'Email terverifikasi' : 'Email belum terverifikasi'}</p><p className="mt-2 text-xs text-slate-500">{user.role_assignments.map((a: any) => a.role.name).join(' · ')}</p></div>
            <ActionForm title="Kelola akun / penugasan" url={route('administration.user', user.id)} fields={[{ name: 'status', label: 'Status akun', type: 'select', options: [{ value: 'active', label: 'Aktif' }, { value: 'pending', label: 'Menunggu' }, { value: 'suspended', label: 'Ditangguhkan' }] }, { name: 'role', label: 'Tambahkan / perbarui penugasan', type: 'select', required: false, options: ['Pegawai', 'Penanggung Jawab Ruangan', 'Koordinator'].map(value => ({ value, label: value })) }, unit, { name: 'room_id', label: 'Ruangan (kosong = cakupan unit)', type: 'select', required: false, options: rooms.map((r: any) => ({ value: r.id, label: r.name })) }, { name: 'ends_at', label: 'Akhir penugasan', type: 'date', required: false }, { name: 'reason', label: 'Alasan perubahan', type: 'textarea' }, { name: 'current_password', label: 'Password Anda (wajib saat menugaskan Koordinator)', type: 'password', required: false }]} initial={{ status: user.status }} />
        </div><div className="mt-4 space-y-2">{user.role_assignments.map((assignment: any) => <div key={assignment.id} className="flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-3"><p className="text-xs text-slate-600">{assignment.role.name} · Unit #{assignment.unit_id || 'Global'} · Ruangan {assignment.room_id || 'seluruh unit'} · Berakhir: {assignment.ends_at || 'belum ditetapkan'}</p>{user.id !== auth.user.id && (!assignment.ends_at || new Date(assignment.ends_at) > new Date()) && (isGlobal || (!assignment.is_global && !assignment.can_administer)) && <ActionForm title="Cabut penugasan" url={route('administration.assignment.revoke', assignment.id)} fields={[{ name: 'reason', label: 'Alasan pencabutan / rencana pengganti', type: 'textarea' }, { name: 'current_password', label: 'Password Anda', type: 'password' }]} description="Akses mandat ini langsung berakhir dan sesi akun diakhiri. Riwayat dipertahankan. Pastikan tugas terbuka ditangani petugas pengganti." />}</div>)}</div></section>)}</div>{!users.data.length && <p className="simon-card text-slate-500">Tidak ada pengguna dalam cakupan administrasi.</p>}<Pagination data={users} />
        <div className="mt-8 grid gap-5 md:grid-cols-3">{[['Unit', units], ['Ruangan', rooms], ['Kategori aset', categories]].map(([title, items]: any) => <section className="simon-card" key={title}><h2 className="mb-4 font-bold">{title}</h2><ul className="space-y-2 text-sm">{items.map((item: any) => <li key={item.id}>{item.name} <span className="text-slate-400">#{item.id}</span></li>)}</ul></section>)}</div>
    </AuthenticatedLayout>;
}
