import { useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import ActionForm from '@/Components/ActionForm';
import Pagination from '@/Components/Pagination';
import StatusBadge from '@/Components/StatusBadge';

export default function Import({ batches, batch, rows }: any) {
    const columnLabels: Record<string, string> = { name: 'Nama barang', category_id: 'ID kategori', room_id: 'ID ruangan', item_code: 'Kode barang', nup: 'NUP', satker_code: 'Kode satker', condition: 'Kondisi', brand_type: 'Merek / tipe (opsional)', value: 'Nilai perolehan (opsional)' };
    const [columnNames, setColumnNames] = useState<Record<string, string>>(Object.fromEntries(Object.keys(columnLabels).map(key => [key, key])));
    const form = useForm<{ file: File | null; sheet: string; column_map: string }>({ file: null, sheet: '', column_map: '' });
    return <AuthenticatedLayout header={<h1 className="text-2xl font-bold">Impor aset · Pratinjau sebelum simpan</h1>}>
        <Head title="Impor aset" />
        <section className="simon-card mb-6"><h2 className="font-bold">Unggah Excel atau CSV UTF-8</h2><p className="my-3 text-sm text-slate-600">Maksimal 10 MB / 1.000 baris. Kolom wajib (pemisah koma):</p><code className="block overflow-x-auto rounded-lg bg-slate-50 p-3 text-xs">name,category_id,room_id,item_code,nup,satker_code,condition</code><p className="mt-2 text-xs text-slate-500">Kondisi: Baik, Rusak Ringan, atau Rusak Berat. ID kategori/ruangan tersedia di administrasi. Kolom opsional: brand_type,value. Impor tidak menimpa aset lama.</p>
            <form onSubmit={e => { e.preventDefault(); form.transform(data => ({ ...data, column_map: JSON.stringify(Object.fromEntries(Object.entries(columnNames).map(([target, source]) => [source.trim() || target, target]))) })); form.post(route('imports.store'), { onSuccess: () => form.reset() }); }} className="mt-5 space-y-3"><label htmlFor="import-file" className="block text-sm font-medium">Berkas XLSX / CSV</label><input id="import-file" className="simon-input" type="file" accept=".xlsx,.csv,.txt" required onChange={e => form.setData('file', e.target.files?.[0] || null)} /><label htmlFor="import-sheet" className="block text-sm font-medium">Nama lembar Excel (opsional)</label><input id="import-sheet" className="simon-input" value={form.data.sheet} onChange={e => form.setData('sheet', e.target.value)} placeholder="Kosongkan untuk lembar pertama" /><details className="rounded-xl border p-3"><summary className="cursor-pointer text-sm font-medium">Pemetaan nama kolom (opsional)</summary><p className="my-3 text-xs text-slate-600">Jika judul di berkas berbeda, isi judul kolom sumber untuk tiap data di bawah. Contoh: isi “Nama Barang” pada data Nama barang.</p><div className="grid gap-3 sm:grid-cols-2">{Object.entries(columnLabels).map(([target, label]) => <label className="text-sm" key={target} htmlFor={`column-${target}`}>{label}<input id={`column-${target}`} className="simon-input mt-1" value={columnNames[target]} onChange={e => setColumnNames(previous => ({ ...previous, [target]: e.target.value }))} /></label>)}</div></details><p className="text-xs text-slate-500">Simpan kode barang, NUP, dan satker sebagai teks agar nol di depan tidak hilang. Rumus Excel ditolak; gunakan nilai tetap. Berkas sumber disimpan privat.</p>{Object.entries(form.errors).map(([key, value]) => <p role="alert" key={key} className="text-sm text-red-700">{value}</p>)}<button className="simon-button" disabled={form.processing}>{form.processing ? 'Membaca berkas…' : 'Buat pratinjau'}</button></form>
        </section>
        {batch && <section className="simon-card mb-6"><div className="mb-4 flex flex-wrap justify-between gap-3"><h2 className="font-bold">{batch.title}</h2><StatusBadge status={batch.status} /></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Barang</th><th className="p-3">NUP</th><th className="p-3">Validasi</th></tr></thead><tbody>{rows.data.map((row: any) => <tr key={row.id} className="border-t"><td className="p-3">{row.raw_data.name || 'Baris tidak valid'}</td><td className="p-3">{row.raw_data.nup}</td><td className="p-3"><StatusBadge status={row.status} /><p className="mt-1 text-red-700">{row.validation_errors}</p>{batch.status === 'preview' && <div className="mt-2"><ActionForm title="Koreksi baris" url={route('imports.correct', [batch.id, row.id])} fields={[...Object.entries(columnLabels).map(([name, label]) => ({ name, label, type: ['category_id', 'room_id', 'value'].includes(name) ? 'number' : 'text', required: !['brand_type', 'value'].includes(name) })), { name: 'reason', label: 'Alasan koreksi', type: 'textarea' }]} initial={{ ...row.raw_data, row_checksum: row.row_checksum }} /></div>}</td></tr>)}</tbody></table></div><Pagination data={rows} />{batch.status === 'preview' && <div className="mt-5"><ActionForm title="Simpan seluruh baris valid" url={route('imports.commit', batch.id)} description="Semua baris akan diperiksa ulang. Jika satu baris bermasalah, tidak ada aset yang ditambahkan. Impor tidak bisa dijalankan dua kali pada batch yang sama." /></div>}</section>}
        <h2 className="mb-4 text-lg font-bold">Riwayat batch saya</h2><div className="space-y-3">{batches.data.map((item: any) => <Link key={item.id} href={route('imports.index', { batch: item.id })} className="simon-card flex justify-between gap-3"><span>{item.title}</span><StatusBadge status={item.status} /></Link>)}</div><Pagination data={batches} />
    </AuthenticatedLayout>;
}
