import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, usePage, usePoll } from '@inertiajs/react';
import ActionForm, { Field } from '@/Components/ActionForm';
import Pagination, { Paginated } from '@/Components/Pagination';
import StatusBadge from '@/Components/StatusBadge';
import { useEffect } from 'react';
import MediaGallery from '@/Components/MediaGallery';
import { PageProps } from '@/types';

export default function Index({ module, title, records, assets, rooms, users, filters }: { module: string; title: string; records: Paginated<any>; assets: any[]; rooms: any[]; users: any[]; filters: { search?: string } }) {
    const { auth } = usePage<PageProps>().props;
    const pendingPhotos = records.data.some(record => record.media?.some((photo: any) => ['queued', 'processing'].includes(photo.processing_status)));
    const { start: startPolling, stop: stopPolling } = usePoll(10000, { only: ['records'] }, { autoStart: false });
    useEffect(() => { if (pendingPhotos) startPolling(); else stopPolling(); return stopPolling; }, [pendingPhotos, startPolling, stopPolling]);
    const asset: Field = { name: 'asset_id', label: 'Barang', type: 'select', options: assets.map(a => ({ value: a.id, label: a.name })) };
    const notes: Field = { name: 'notes', label: 'Catatan / hasil pemeriksaan', type: 'textarea' };
    const condition: Field = { name: 'condition', label: 'Kondisi fisik', type: 'select', options: ['Baik', 'Rusak Ringan', 'Rusak Berat'].map(value => ({ value, label: value })) };
    const completeness: Field = { name: 'completeness', label: 'Kelengkapan barang dan aksesori', type: 'select', options: [{ value: 'complete', label: 'Lengkap' }, { value: 'incomplete', label: 'Tidak lengkap; perlu tindak lanjut' }] };
    const document: Field = { name: 'document', label: 'Dokumen PDF bertanda tangan (maks. 10 MB)', type: 'file' };
    const start: Field = { name: 'start_date', label: 'Tanggal mulai', type: 'date' };
    let create: { url: string; fields: Field[] } | null = null;
    if (module === 'inventory' && auth.can.coordinate) create = { url: route('inventory.store'), fields: [{ name: 'name', label: 'Nama sesi' }, start, { ...asset, name: 'asset_ids', label: 'Barang yang diperiksa', type: 'multiselect', hint: 'Pilih barang dari satu ruangan. Buat sesi terpisah untuk ruangan lain.' }] };
    if (module === 'maintenance' && auth.can.coordinate) create = { url: route('maintenance.store'), fields: [asset, { name: 'description', label: 'Pekerjaan perawatan', type: 'textarea' }, { name: 'cost', label: 'Biaya (Rp)', type: 'number', required: false }, start] };
    if (module === 'spip' && auth.can.coordinate) create = { url: route('spip.store'), fields: [asset, { name: 'period', label: 'Periode', type: 'month' }, { name: 'risk_description', label: 'Risiko', type: 'textarea' }, { name: 'control_action', label: 'Rencana pengendalian', type: 'textarea' }, { name: 'due_date', label: 'Tenggat tindak lanjut', type: 'date', required: false }] };
    if (['incidents', 'transfers', 'registers'].includes(module)) create = { url: module === 'registers' ? route('identities.store') : route('workspace.store', module), fields: [asset, { name: 'title', label: 'Judul catatan' }, notes,
        ...(module === 'transfers' ? [{ name: 'target_room_id', label: 'Ruangan tujuan', type: 'select', options: rooms.map(room => ({ value: room.id, label: room.name })) }] : []),
        ...(module === 'incidents' ? [{ name: 'category', label: 'Jenis kejadian', type: 'select', options: [{ value: 'damage', label: 'Kerusakan' }, { value: 'missing', label: 'Kehilangan' }, { value: 'other', label: 'Lainnya' }] }, { name: 'images', label: 'Foto bukti', type: 'images', required: false, hint: 'Maksimal 4 foto JPEG, PNG, atau WebP; masing-masing 10 MB. Foto tampilan otomatis dikompres ke WebP, sumber asli disimpan privat.' }] : []),
        ...(module === 'registers' ? [{ name: 'register_type', label: 'Jenis register', type: 'select', options: [{ value: 'ASP', label: 'ASP' }, { value: 'PSP', label: 'PSP' }] }, { name: 'reference_number', label: 'Nomor dokumen' }, { name: 'reference_date', label: 'Tanggal dokumen', type: 'date' }, { name: 'source_status', label: 'Status pada sumber resmi', hint: 'Dicatat sesuai bukti; SIMON tidak terhubung langsung ke sistem pemerintah.' }, { name: 'ticket_number', label: 'Nomor tiket rekonsiliasi', required: false }, { name: 'bast_number', label: 'Nomor BAST rujukan' }, { name: 'satker_code', label: 'Kode satker setelah transisi' }, { name: 'item_code', label: 'Kode barang setelah transisi' }, { name: 'nup', label: 'NUP setelah transisi', hint: 'Teks; nol di depan dipertahankan.' }, document] : []),
    ] };
    return <AuthenticatedLayout header={<div className="flex flex-wrap items-center justify-between gap-4"><h1 className="text-2xl font-bold">{title}</h1>{create && <ActionForm title={'Tambah · ' + title} url={create.url} fields={create.fields} />}{module === 'reports' && <a className="simon-button" href={route('reports.export')}>Ekspor CSV</a>}</div>}>
        <Head title={title} />
        {module === 'reports' && <Link className="simon-button-secondary mb-5" href={route('reports.snapshots')}>Snapshot laporan & ekspor PDF / Excel</Link>}
        <p className="mb-6 text-sm text-slate-500">Data mengikuti cakupan akses Anda. Setiap perubahan penting dicatat dalam jejak audit.</p>
        {['reports', 'incidents', 'transfers', 'registers'].includes(module) && <form className="mb-5 flex gap-2" method="get"><label className="sr-only" htmlFor="record-search">Cari data</label><input id="record-search" name="search" defaultValue={filters.search || ''} placeholder="Cari nama atau judul…" className="simon-input max-w-md" /><button className="simon-button-secondary">Cari</button></form>}
        {['custody', 'disposals'].includes(module) && <div className="simon-card mb-6"><h2 className="mb-3 font-semibold">Mulai dari barang</h2><div className="max-h-64 space-y-3 overflow-y-auto">{assets.filter(a => a.status === 'active').map(a => <div key={a.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-2"><span className="text-sm">{a.name}</span>
            {module === 'custody' && auth.can.coordinate && <ActionForm title="Ajukan penetapan" url={route('custody.assign', a.id)} fields={[{ name: 'user_id', label: 'Pemegang', type: 'select', options: users.map(u => ({ value: u.id, label: u.name })) }, start, notes]} />}
            {module === 'disposals' && <ActionForm title="Usulkan penghapusan" url={route('disposal.propose', a.id)} fields={[{ name: 'reason', label: 'Alasan usulan', type: 'textarea' }]} />}
        </div>)}</div></div>}
        <div className="space-y-4">{records.data.map(record => <section key={record.id} className="simon-card">
            <div className="flex flex-wrap items-start justify-between gap-3"><h2 className="font-semibold">{module === 'notifications' ? record.data.title : record.title || record.name || record.bast_number || record.asset?.name || record.action || '#' + record.id}</h2>{record.status && <StatusBadge status={record.status} />}</div>
            {record.user?.name && <p className="mt-2 text-sm">Pemegang: {record.user.name}</p>}
            {record.asset?.name && record.title && <p className="mt-2 text-sm text-slate-500">{record.asset.name}</p>}
            <p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{record.description || record.reason || record.risk_description || record.notes || record.data?.notes || record.data?.message}</p>
            {record.due_date && <p className="mt-2 text-sm">Tenggat: {record.due_date}</p>}
            {record.followup && <p className="mt-2 text-sm">Tindak lanjut: {record.followup}</p>}
            {record.effectiveness && <p className="mt-2 text-sm">Evaluasi: {record.effectiveness}</p>}
            {record.control_action && <p className="mt-2 text-sm">Pengendalian: {record.control_action}</p>}
            {record.data?.loan_request_id && <p className="mt-2 text-sm"><Link className="font-semibold text-[#015850]" href={route('loans.show', record.data.loan_request_id)}>Peminjaman #{record.data.loan_request_id}</Link> · Kondisi awal: {record.data.condition_before || 'Belum tercatat'} · Pengembalian: {record.data.condition_after}. Temuan ini bukan penetapan tanggung jawab atau tagihan.</p>}
            {record.result_notes && <p className="mt-2 text-sm">Hasil perawatan: {record.result_notes}</p>}
            {record.data?.checked_notes && <p className="mt-2 text-sm">Hasil pemeriksaan: {record.data.checked_condition} · {record.data.checked_notes}</p>}
            {record.data?.custody_assignment_id && <p className="mt-2 text-sm">Temuan penetapan #{record.data.custody_assignment_id} · Sebelum: {record.data.condition_before || 'Belum tercatat'} · Kembali: {record.data.condition_after}. Ini catatan pemeriksaan, bukan penetapan tanggung jawab atau tagihan.</p>}
            {module === 'custody' && record.condition_after && <p className="mt-2 text-sm">Kondisi serah: {record.condition_before || 'Belum tercatat'} · Kembali: {record.condition_after} · Kelengkapan: {record.return_completeness === 'complete' ? 'Lengkap' : 'Tidak lengkap'} · {record.return_notes}</p>}
            {record.media?.length > 0 && <div className="mt-4"><MediaGallery photos={record.media} poll={false} /></div>}
            {module === 'reports' && <p className="mt-2 text-sm">NUP {record.nup || '—'} · {record.room?.name || 'Tanpa ruangan'} · {record.condition}</p>}
            {module === 'registers' && <p className="mt-2 text-sm">{record.data.register_type} · {record.data.reference_number} · {record.data.reference_date}</p>}
            {module === 'registers' && record.data.before_identity && <div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><p>Status sumber: {record.data.source_status} · Pemetaan: {record.data.mapping_status}</p><p>Identitas lama: {record.data.before_identity.satker_code || '—'} / {record.data.before_identity.item_code || '—'} / {record.data.before_identity.nup || '—'}</p><p>Identitas usulan: {record.data.after_identity.satker_code} / {record.data.after_identity.item_code} / {record.data.after_identity.nup}</p><p>BAST: {record.data.bast_number} · Tiket: {record.data.ticket_number || '—'}</p><a className="mt-2 inline-block font-semibold text-[#015850] underline" href={route('identities.evidence', record.id)}>Unduh bukti transisi</a></div>}
            <div className="mt-4 flex flex-wrap gap-2">
                {module === 'spip' && <Link className="simon-button-secondary" href={route('documents.index', { spip: record.id })}>Buka arsip bukti SPIP</Link>}
                {module === 'spip' && auth.can.inspect && ['open', 'revision_requested'].includes(record.status) && <ActionForm title="Laporkan tindak lanjut" url={route('spip.action', [record.id, 'submit'])} fields={[notes, document]} initial={{ version: record.version }} />}
                {module === 'spip' && auth.can.coordinate && record.assigned_to !== auth.user.id && record.status === 'review' && <><ActionForm title="Nilai efektivitas & tutup" url={route('spip.action', [record.id, 'resolve'])} fields={[notes]} initial={{ version: record.version }} /><ActionForm title="Minta perbaikan kontrol" url={route('spip.action', [record.id, 'revise'])} fields={[notes]} initial={{ version: record.version }} /></>}
                {module === 'incidents' && record.canInspectFollowup && record.status === 'approved' && !record.data?.maintenance_id && <ActionForm title="Periksa hasil tindak lanjut" url={route('records.action', [record.id, 'inspect-resolution'])} fields={[condition, notes]} initial={{ version: record.version }} />}
                {module === 'incidents' && record.canStartMaintenance && record.status === 'approved' && (record.data?.loan_item_id || record.data?.custody_assignment_id) && <ActionForm title={record.data.maintenance_id ? 'Catat perawatan lanjutan' : 'Mulai perawatan barang'} url={route('maintenance.store')} fields={[{ name: 'description', label: 'Pekerjaan perawatan', type: 'textarea' }, { name: 'cost', label: 'Biaya perawatan (bukan tagihan pemegang)', type: 'number', required: false }, start]} initial={{ asset_id: record.asset_id, incident_id: record.id }} />}
                {module === 'incidents' && auth.can.inspect && record.data?.maintenance_id && <Link className="simon-button-secondary" href={route('workspace.index', 'maintenance')}>Buka pemeriksaan perawatan</Link>}
                {module === 'custody' && auth.can.coordinate && <ActionForm title="Buat draf BAST penetapan" url={route('documents.store')} initial={{ parent_type: 'custody', parent_id: record.id, template: 'bast_personal' }} />}
                {module === 'transfers' && auth.can.coordinate && <ActionForm title="Buat draf BAST distribusi" url={route('documents.store')} initial={{ parent_type: 'record', parent_id: record.id, template: 'bast_collective' }} />}
                {module === 'inventory' && <Link className="simon-button-secondary" href={route('inventory.show', record.id)}>Periksa {record.items_count} barang</Link>}
                {module === 'maintenance' && record.canInspectMaintenance && record.status === 'in_progress' && <ActionForm title="Periksa hasil perawatan" url={route('maintenance.complete', record.id)} fields={[condition, notes]} />}
                {module === 'disposals' && auth.can.coordinate && record.proposed_by !== auth.user.id && record.status === 'proposed' && <ActionForm title="Catat persetujuan dengan SK" url={route('disposal.approve', record.id)} fields={[{ name: 'sk_number', label: 'Nomor SK' }, { name: 'sk_date', label: 'Tanggal SK', type: 'date' }, { name: 'sk_issuer', label: 'Pejabat penerbit SK' }, document]} />}
                {module === 'documents' && <Link className="simon-button-secondary" href={route('loans.show', record.reference_id)}>Lihat transaksi & dokumen</Link>}
                {module === 'notifications' && <>{!record.read_at && <ActionForm title="Tandai telah dibaca" url={route('notifications.read', record.id)} />}{record.data.url && <Link className="simon-button-secondary" href={record.data.url}>Lihat aktivitas</Link>}</>}
                {module === 'audit' && <p className="text-xs text-slate-500">{record.created_at} · Objek #{record.subject_id} · Pengguna #{record.user_id || 'Sistem'}</p>}
                {module === 'custody' && <>
                    {auth.can.inspect && record.user_id !== auth.user.id && record.status === 'pending' && <ActionForm title="Periksa & serahkan" url={route('custody.action', { assignment: record.id, action: 'handover' })} fields={[document, notes]} />}
                    {record.user_id === auth.user.id && record.status === 'handed_over' && <ActionForm title="Konfirmasi diterima" url={route('custody.action', { assignment: record.id, action: 'accept' })} />}
                    {record.user_id === auth.user.id && record.status === 'active' && <ActionForm title="Ajukan penarikan" url={route('custody.action', { assignment: record.id, action: 'request-return' })} />}
                    {auth.can.inspect && record.user_id !== auth.user.id && (record.status === 'return_requested' || (record.status === 'received' && !record.hasReturnEvidence)) && <ActionForm title="Periksa pengembalian" url={route('custody.action', { assignment: record.id, action: 'receive' })} fields={[condition, completeness, notes, document]} />}
                    {record.hasHandoverEvidence && <a className="simon-button-secondary" href={route('custody.evidence', [record.id, 'handover'])}>BAST penyerahan</a>}
                    {record.hasReturnEvidence && <a className="simon-button-secondary" href={route('custody.evidence', [record.id, 'return'])}>BAST pengembalian</a>}
                    {auth.can.coordinate && record.user_id !== auth.user.id && record.received_by !== auth.user.id && record.status === 'received' && record.hasReturnEvidence && <ActionForm title="Verifikasi bukti & tutup penetapan" url={route('custody.revoke', record.id)} fields={[notes]} description="Periksa bukti BAST pengembalian dan hasil tindak lanjut sebelum menyetujui penutupan. Barang tetap tercatat dalam penetapan sampai tahap ini selesai." />}
                    {auth.can.coordinate && record.status === 'pending' && <ActionForm title="Tolak penetapan" url={route('custody.action', { assignment: record.id, action: 'reject' })} fields={[notes]} />}
                </>}
                {['incidents', 'transfers', 'registers'].includes(module) && <>
                    {record.canReview && record.status === 'submitted' && (record.data?.loan_item_id || record.data?.custody_assignment_id ? ['approve'] : ['approve', 'reject']).map(action => <ActionForm key={action} title={action === 'approve' ? 'Setujui tindak lanjut' : 'Tolak dengan alasan'} url={route('records.action', { record: record.id, action })} fields={[notes, ...(module === 'registers' && action === 'approve' ? [{ name: 'mapping_verified', label: 'Verifikasi identitas barang yang sama dan bukti resmi', type: 'select', options: [{ value: '1', label: 'Sudah saya cocokkan secara independen' }] }] : [])]} initial={{ version: record.version }} />)}
                    {auth.can.inspect && module === 'transfers' && ['approved', 'in_transit'].includes(record.status) && <ActionForm title={record.status === 'approved' ? 'Serahkan ke ruangan tujuan' : 'Konfirmasi penerimaan ruangan'} url={route('records.action', { record: record.id, action: record.status === 'approved' ? 'handover' : 'receive' })} fields={record.status === 'approved' ? [document, notes] : [notes]} initial={{ version: record.version }} />}
                    {record.canResolve && module === 'incidents' && record.status === 'approved' && <ActionForm title="Catat penyelesaian" url={route('records.action', { record: record.id, action: 'resolve' })} fields={[notes]} initial={{ version: record.version }} />}
                    {record.canReview && module === 'registers' && record.status === 'approved' && record.data.mapping_status === 'verified' && <ActionForm title="Terapkan identitas terverifikasi" url={route('identities.apply', record.id)} fields={[notes]} initial={{ version: record.version }} description="Identitas master akan diubah sesuai usulan yang telah diverifikasi. ID internal dan riwayat transaksi tidak berubah; identitas lama tetap diarsipkan. Ruangan tidak dipindahkan oleh tindakan ini." />}
                </>}
            </div>
        </section>)}</div>{!records.data.length && <p className="simon-card text-center text-slate-500">Belum ada data pada daftar ini.</p>}
        <Pagination data={records} />
    </AuthenticatedLayout>;
}
