import MediaGallery from '@/Components/MediaGallery';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';

export default function Show({ asset, canEdit }: any) {
    return <AuthenticatedLayout header={<><Link className="text-sm text-[#015850]" href={route('assets.index')}>← Katalog aset</Link><div className="mt-3 flex flex-wrap justify-between gap-4"><h1 className="text-2xl font-bold">{asset.name}</h1><div className="flex flex-wrap gap-2">{canEdit && <Link className="simon-button" href={route('assets.edit', asset.id)}>Edit data</Link>}<Link className="simon-button-secondary" href={route('assets.qrcode', asset.id)}>Label QR</Link></div></div></>}>
        <Head title={asset.name} /><div className="grid gap-6 lg:grid-cols-3"><section className="simon-card"><h2 className="mb-4 font-semibold">Foto barang</h2><MediaGallery photos={asset.media || []} />{!asset.media?.length && <p className="py-16 text-center text-sm text-slate-400">Belum ada foto</p>}</section>
        <section className="simon-card lg:col-span-2"><h2 className="mb-5 text-lg font-bold">Identitas & kondisi</h2><dl className="grid gap-5 sm:grid-cols-2">{[['Kode barang', asset.item_code], ['NUP', asset.nup], ['Satker', asset.satker_code], ['Kategori', asset.category?.name], ['Merek / tipe', asset.brand_type], ['Nomor seri', asset.serial_number], ['Ruangan', asset.room?.name], ['Kondisi', asset.condition], ['Status', asset.status], ['Kebijakan peminjaman', asset.is_loanable ? 'Dapat diajukan' : 'Tidak dipinjamkan'], ['Tanggal perolehan', asset.acquisition_date], ...(asset.value !== undefined ? [['Nilai perolehan', new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(Number(asset.value || 0))]] : [])].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm font-medium">{value || '—'}</dd></div>)}</dl><h3 className="mb-2 mt-6 text-sm font-semibold">Spesifikasi</h3><p className="whitespace-pre-wrap text-sm text-slate-600">{asset.specification || 'Belum dicatat.'}</p>
            {asset.is_loanable && asset.status === 'active' && <div className="mt-7"><Link className="simon-button" href={route('loans.create')}>Ajukan peminjaman</Link><p className="mt-2 text-xs text-slate-500">Ketersediaan jadwal diperiksa kembali saat persetujuan.</p></div>}
            {canEdit && <p className="mt-6 rounded-xl bg-amber-50 p-3 text-sm">Perubahan ruangan melalui menu Mutasi. Penghapusan aset melalui Usulan Penghapusan dengan bukti SK; riwayat tidak dihapus permanen.</p>}
        </section></div>
        {asset.identifiers?.length > 0 && <section className="simon-card mt-6"><h2 className="mb-4 font-bold">Riwayat identitas BMN</h2><p className="mb-3 text-sm text-slate-500">ID internal tetap sama. Tanggal awal yang tidak diketahui tidak diisi otomatis.</p><div className="space-y-3">{asset.identifiers.map((identity: any) => <div key={identity.id} className="rounded-xl border p-3 text-sm"><p>{identity.identity_snapshot ? `${identity.identity_snapshot.satker_code || '—'} / ${identity.identity_snapshot.item_code || '—'} / ${identity.identity_snapshot.nup || '—'}` : identity.identifier_value}</p><p className="text-slate-500">Mulai: {identity.assigned_date?.slice(0, 10) || 'Tidak diketahui'} · Berakhir: {identity.valid_until?.slice(0, 10) || '—'} · Register #{identity.work_record_id || '—'}</p></div>)}</div></section>}
    </AuthenticatedLayout>;
}
